# Generated by Django 3.2 on 2022-05-23 05:55

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cliente_id', models.AutoField(primary_key=True, serialize=False)),
                ('cliente_nombre', models.CharField(max_length=100)),
                ('cliente_apellido', models.CharField(max_length=100)),
                ('cliente_email', models.EmailField(max_length=254)),
                ('cliente_telefono', models.CharField(max_length=100)),
                ('cliente_direccion', models.CharField(max_length=100)),
                ('cliente_pais', models.CharField(max_length=100)),
                ('cliente_ciudad', models.CharField(max_length=100)),
                ('cliente_fecha_nacimiento', models.DateField()),
                ('cliente_foto', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_id', models.AutoField(primary_key=True, serialize=False)),
                ('region_nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('tour_id', models.AutoField(primary_key=True, serialize=False)),
                ('tour_nombre', models.CharField(max_length=100)),
                ('tour_descripcion', models.TextField()),
                ('tour_itinerario', models.TextField()),
                ('tour_precio', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='precio')),
                ('tour_foto', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('tour_stock', models.IntegerField(default=0)),
                ('tour_fecha_inicio', models.DateField()),
                ('tour_fecha_fin', models.DateField()),
                ('region_id', models.ForeignKey(db_column='region_id', on_delete=django.db.models.deletion.CASCADE, related_name='Tour', to='tours.region', verbose_name='region')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('compra_id', models.AutoField(primary_key=True, serialize=False)),
                ('compra_fecha', models.DateField()),
                ('compra_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='total')),
                ('compra_cantidad', models.IntegerField(default=0)),
                ('cliente_id', models.ForeignKey(db_column='cliente_id', on_delete=django.db.models.deletion.CASCADE, related_name='Compra', to='tours.cliente', verbose_name='cliente')),
                ('tour_id', models.ForeignKey(db_column='tour_id', on_delete=django.db.models.deletion.CASCADE, related_name='Compra', to='tours.tour', verbose_name='tour')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='compra_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.compra'),
        ),
    ]
